### ISSUE TITLE
Publish a v0.1.0

### ISSUE THREAD

**Issue by AdrieanKhisbe** [concon121/serverless-plugin-nested-stacks#5]
If you battle tested your plugin, 
you should consider publish a minor to indicate a better confidence in the working of your plugin.

(I tryied it and works well, but hesitate to do so because of the version)

**Comment by concon121** [comment]
Published version 0.1.0 https://www.npmjs.com/package/serverless-aws-nested-stacks

**Comment by AdrieanKhisbe** [comment]
Awesome!
